package fitreminder;

    import java.sql.*;
    import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class EditData extends javax.swing.JFrame {
    private Workout parent;
    private int selectedRow;
    
    public EditData(Workout parent, int selectedRow) {
        this.parent = parent;
        this.selectedRow = selectedRow;
        initComponents();
        loadData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cbxJenis = new javax.swing.JComboBox<>();
        txtAktivitas = new javax.swing.JTextField();
        txtWaktu = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Edit Data");

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Olahraga");

        jLabel4.setText("Aktivitas");

        jLabel5.setText("Waktu");

        cbxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Push Up", "Sit Up", "Pull Up", "Plank" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(186, 186, 186)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama)
                                .addComponent(cbxJenis, 0, 292, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtAktivitas))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtWaktu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnSimpan)
                        .addGap(52, 52, 52)
                        .addComponent(btnBatal)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        
        this.dispose();
        
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = txtNama.getText();
    String aktivitas = txtAktivitas.getText();
    String jenis_olahraga = cbxJenis.getSelectedItem().toString();
    String waktu = txtWaktu.getText();

    if (nama.isEmpty() || aktivitas.isEmpty() || jenis_olahraga.isEmpty() || waktu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
        return;
    }

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang valid terlebih dahulu.");
        return;
    }

    try {
        DefaultTableModel model = (DefaultTableModel) parent.getTableModel();
        
        if (selectedRow >= 0 && selectedRow < model.getRowCount()) {
            String namaLama = model.getValueAt(selectedRow, 0).toString();
            
            Connection con = DB_Connector.getConnection();
            String query = "UPDATE data_user SET nama = ?, aktivitas = ?, jenis_olahraga = ?, waktu = ? WHERE nama = ?";
            PreparedStatement ps = con.prepareStatement(query);

            ps.setString(1, nama);
            ps.setString(2, aktivitas);
            ps.setString(3, jenis_olahraga);
            ps.setString(4, waktu);
            ps.setString(5, namaLama);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
                parent.loadData();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Baris yang dipilih tidak valid.");
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void loadData() {
        
        if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) parent.getTableModel();
        
        String nama = model.getValueAt(selectedRow, 0).toString();
        String aktivitas = model.getValueAt(selectedRow, 1).toString();
        String jenisOlahraga = model.getValueAt(selectedRow, 2).toString();
        String waktu = model.getValueAt(selectedRow, 3).toString();
        
        txtNama.setText(nama);
        txtAktivitas.setText(aktivitas);
        cbxJenis.setSelectedItem(jenisOlahraga);
        txtWaktu.setText(waktu);
    } else {
        JOptionPane.showMessageDialog(this, "Pilih data yang valid.");
    }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbxJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAktivitas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables
}
